Feat/64 application config
f-lab-clone/ticketing-backend pull request #103
Opened 2023-10-05 06:12 UTC by minjun3021

#  What is this PR?
- Github Issue: #64 

# Key Changes
application설정 파일 타입 변경 .properties -> .yaml
TestController 비활성화 -> test profile일때만 활성화 되게 함

yml 장점
계층적인 데이터 구조를 쉽게 표현할 수 있음.
들여쓰기를 이용해 구조를 명확하게 나타낼 수 있으므로, 복잡한 설정도 명확하게 표현할 수 있음.
yml 단점 
들여쓰기에 민감하여, 들여쓰기가 잘못되면 의도한대로 동작 하지 않을수있음.

# Test Checklist

2023-10-05 06:22 UTC, junha-ahn requested changes

2023-10-05 06:22 UTC, junha-ahn commented on src/integrationTest/resources/application.yml
해당 설정을 주입하면 `Profile('Test')`로 인식되나요?

2023-10-05 06:22 UTC, junha-ahn commented on src/main/resources/application.yml
> local, development 환경에 따른 application.properties 파일 분리 

위를 위해서 `application-development,yml`, `application-local.yml` 파일로 분리되야할것 같습니다 
- AWS환경에서는 `application-development,yml` 파일을 주입해 실행
- Local환경에서는 `application-local.yml` 파일을 주입해 실행

그리고 실행시 어떻게 실행해야하는지도 필요합니다. 

`ENV=development ./gradlew start`

2023-10-05 06:27 UTC, minjun3021 commented on src/integrationTest/resources/application.yml
[application.yml](https://github.com/f-lab-clone/ticketing-backend/pull/103/files/a3b0155384cd1935220f5fa9fae4f3bec840a261#diff-72f9dbb36f304047c35244ecd6958fdd7dcafaa107df67759323d1e85e3abb9c)
파일은 전역 설정입니다.

@Profile("test") ->test 프로필 에서만 활성화 
@ActiveProfiles("test") -> 테스트 수행 시에 어떤 profile을 사용할 것인지 정해주는 어노테이션

2023-10-05 06:40 UTC, minjun3021 commented on src/main/resources/application.yml
aws 환경일때 어떤 속성들을  추가해야하는지 예시로 알수있을까요?

2023-10-05 06:47 UTC, minjun3021 commented on src/integrationTest/resources/application.yml
아닙니다 따로 프로필 설정을 하지 않은 상태라 Profile은 default로 인식합니다

@Profile("test") ->test 프로필 에서만 활성화 
@ActiveProfiles("test") -> 테스트 수행 시에 해당클래스에서만 어떤 profile을 사용할 것인지 정해주는 어노테이션

2023-10-05 06:49 UTC, junha-ahn commented on src/integrationTest/resources/application.yml
설정 파일에 `ENV=TEST`로 주입하는게 더 간단하지 않나요?

2023-10-05 06:49 UTC, junha-ahn commented on src/main/resources/application.yml
현재는 ddl 관련 옵션을 제거하는정도 일것 같네요.

2023-10-08 11:16 UTC, junha-ahn commented on src/main/resources/application.yml
그리고 실행할때 어떻게 **두개의 컨피그 중 하나를 선택**해서 실행하는지도 알려주세요. (실제 AWS Cloud 환경에서 해당 명령을 통해 실행 가능해야합니다)

2023-10-08 11:16 UTC, junha-ahn commented on src/main/resources/application.yml
그리고 실행할때 어떻게 **두개의 컨피그 중 하나를 선택**해서 실행하는지도 알려주세요. (실제 AWS Cloud 환경에서 해당 명령을 통해 실행 가능해야합니다)

2023-10-08 11:16 UTC, junha-ahn commented on src/main/resources/application.yml
그리고 실행할때 어떻게 **두개의 컨피그 중 하나를 선택**해서 실행하는지도 알려주세요. (실제 AWS Cloud 환경에서 해당 명령을 통해 실행 가능해야합니다)

2023-10-08 14:59 UTC, minjun3021 commented on src/main/resources/application.yml
그럼 dev환경에서는 JWT 관련 값 을 환경변수를 이용하나요?

2023-10-09 04:39 UTC, junha-ahn commented on src/main/resources/application.yml
넵 맞습니다. 

```dotenv
# DEV
jwt=${jwt_config}
```

```dotenv
# local
jwt=a412adfasdf
```

2023-10-09 07:02 UTC, minjun3021 commented
![ide profile set](https://github.com/f-lab-clone/ticketing-backend/assets/33713012/5823a33f-5cda-433c-b6de-62c2778d65ba)
idel로 실행시 프로필 세팅 예시



gralde 로 실행시 예시 
./gradlew bootRun  (default프로필은 local)
./gradlew bootRun -P spring.profiles.active=local (프로필 =local)
./gradlew bootRun -P spring.profiles.active=dev (프로필 =dev)

2023-10-09 07:05 UTC, junha-ahn commented
@ParkJeongseop 해당 브랜치 리뷰 부탁드립니다. 

그리고 Open-docs 에러도 확인 부탁드려요.

2023-10-10 13:51 UTC, ParkJeongseop commented
docker-compose로 실행하는경우는 어떻게실행하나요?
그리고 컨플릭트 해결부탁드려요

2023-10-10 13:53 UTC, junha-ahn commented
`docker-compose up` 명령어로 실행될때 `local config file`을 잘 받도록 수정 필요해보이네요. 
- [ ] `docker-compose.yml` 파일 수정 (argument 등 키워드로 검색 부탁드립니다)

2023-10-12 16:40 UTC, minjun3021 commented
```
 build:
      args:
        SPRING_PROFILES_ACTIVE: local
```

```
api:
    environment:
      SPRING_PROFILES_ACTIVE: local
```

현재 docker-compose.yml에 두곳을 수정하면 프로필과함께 실행가능합니다.
이 작업 자체는 얼마 안걸렸으나 몇가지 시도를 해봤었는데

docker-compose.yml에 직접 작성하지않고
build할때 arg를 직접 전달하는 방법을 시도해보았는데
dockerFile에서 ENV를 지정해줬음에도 불구하고 런타임시에 적용이 안되어 되게 해보려다가 결국 실패.

2023-10-12 16:49 UTC, minjun3021 commented
[시도해본것]

FROM openjdk:17-jdk-slim as builder
COPY gradlew .
COPY settings.gradle.kts .
COPY build.gradle.kts .
COPY gradle gradle
COPY src src
RUN chmod +x ./gradlew
**ARG SPRING_PROFILES_ACTIVE**
RUN echo $SPRING_PROFILES_ACTIVE
**RUN ./gradlew clean bootjar -Pspring.profiles.active=$SPRING_PROFILES_ACTIVE**
RUN java -Djarmode=layertools -jar build/libs/*.jar extract

FROM openjdk:17-jdk-slim as runtime
COPY --from=builder dependencies/ ./
COPY --from=builder snapshot-dependencies/ ./
COPY --from=builder spring-boot-loader/ ./
COPY --from=builder application/ ./

**ENV SPRING_PROFILES_ACTIVE $SPRING_PROFILES_ACTIVE**
ENTRYPOINT ["java","-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}", "org.springframework.boot.loader.JarLauncher"]

docker-compose.yml에는 프로필 관련 정보를 안적은 상태에서
이렇게 Dockerfile을 작성하고
docker-compose build --build-arg SPRING_PROFILES_ACTIVE="dev" 이렇게 빌드를하고 
docker-compose up을 했을때 runtime시에 ${SPRING_PROFILES_ACTIVE}를 못찾는거같습니다

도커를 잘아시는분있으면 조언 부탁드려요
@junha-ahn @ParkJeongseop

2023-10-12 16:54 UTC, junha-ahn commented
그래도 generate open docs는 실패하네요. 뭘까요 

일단 이 문제에 대한 부분은 이런것 같습니다.

yaml 파일에서 `build` 아래 컨피그 값은 실제로 docker-compose build 나 up을 할때 이미지를 빌드하는 과정에 주입되는 값입니다.
- `RUN ./gradlew clean bootjar -Pspring.profiles.active=$SPRING_PROFILES_ACTIVE` 이때 사용하는 값인거죠

그리고 environment 밑에 있는 컨피그 값은 해당 이미지로부터 컨테이너가 실행될때 주입되는 값이죠 
- 스프링 앱(=러닝 프로세스)에 주입되는 값

따라서 build 밑에 컨피그는 스프링앱이 빌드할때, 즉 local properties 파일을 포함해서 빌드되도록 하는 역할
enviroment 밑의 컨피그는 spring runtime에 주입하는 값 


> 제 개인적 추축입니다. (따로 자료조사하진않았습니다)

2023-10-12 16:56 UTC, junha-ahn commented
왜 실패일지… 흠 

![IMG_1983](https://github.com/f-lab-clone/ticketing-backend/assets/41976906/b5d7f321-0d91-4ec3-b6ff-e3ce43d3831f)

2023-10-14 06:17 UTC, merged