Feat/52 api page and search
f-lab-clone/ticketing-backend pull request #104
Opened 2023-10-05 16:26 UTC by minjun3021

#  What is this PR?
- Github Issue: #52

# Key Changes

# Test Checklist

2023-10-06 03:04 UTC, junha-ahn requested changes
### PR이 너무 거대해져서 보기가 힘드네요.

@ParkJeongseop 

> 모든 PR은 200 ~ 300줄 내외가 되고 1~2일 이내에 리뷰를 완료하여 리뷰의 병목을 해소할 수 있었습니다 [뱅크샐러드](https://blog.banksalad.com/tech/banksalad-code-review-culture/)

물런 신규 기능 추가에 200 ~ 300 줄은 무리겠지만, 앞으로는 단위를 조금 더 쪼개거나, 한 PR에 담더라도, 중간 리뷰 요청해주세요. (PR의 목적은 단순 기능 추가 보다는 코드 리뷰에 중점이 있다고 생각합니다)

현재도 리뷰 남기지만 전체 흐름 파악은 불가능하고, 그냥 단순히 한줄한줄 단위로 읽었습니다.

### 전체적 개선사항
- 추가한 기능에 대한 테스트 코드 추가
- 전체적으로 page, sort 관련 테스트 추가해주세요. (coverage rule 관련해서도 추가 테스트 코드가 필요해보입니다)
- empty list의 경우 `{ data: [] }`를 리턴한다는 테스트 코드를 컨트롤러테스트로 만들어주세요.
- 전체적으로 header에 Setting하는 방식의 자동화가 필요해보입니다. 현재와 같은 방식은 사용불가능해보입니다. (개발자가 직접 기억하고, 필요한 헤더를 세팅해야 한다)

2023-10-07 10:09 UTC, minjun3021 commented on build.gradle.kts
> +                minimum = "0.1".toBigDecimal()
현재 코드로 원래 기준으로 만족합니다. 테스트가 작동안되서 잠깐 바꾸신듯 합니다

2023-10-07 10:40 UTC, minjun3021 commented on src/test/kotlin/com/group4/ticketingservice/health/HealthControllerTest.kt
> +    includeFilters = [ComponentScan.Filter(value = [(SecurityConfig::class), (GsonConfig::class), (OffsetDateTimeAdapter::class), (JwtAuthorizationEntryPoint::class), (TokenProvider::class)], type =
예, 클래스마다 필요로 한 Bean이 다르기 때문에 매번 적어주어야합니다.
저기에 적히는 클래스들은 test시 포함되는 객체들중에 모킹이 힘든 것들입니다

2023-10-07 10:47 UTC, minjun3021 commented on src/integrationTest/kotlin/com/group4/ticketingservice/actuator/ActuatorTest.kt
> +            .andExpect(MockMvcResultMatchers.jsonPath("$.data._links").exists())
제외 시켰습니다

2023-10-07 11:26 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/controller/EventController.kt
> +        @PageableDefault(size = 10, sort = ["date", "id"]) pageable: Pageable
분리되어있습니다. 저기 default  설정은 date,id 오름차순으로 설정 되어있네요 

/events?page=0&size=3&sort=id,desc&sort=username,desc 
이렇게 요청 가능 합니다

2023-10-07 15:40 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/controller/BookmarkController.kt
> +        headers.set("Content-Location", "/bookmarks/%d".format(savedBookmark.id!!))
요청 처리 전/후에 공통적인 작업을 하기 좋은곳인 interceptor나 filter에서 시도를 해볼까했지만
위에 두곳에서 비지니스 로직의 결과에 접근할수없습니다
컨트롤러 레이어에서 header를 set하는  이 방법을 유지 하면될거같습니다.

2023-10-07 17:22 UTC, minjun3021 commented on src/test/kotlin/com/group4/ticketingservice/reservation/ReservationControllerTest.kt
> +            .andExpect(jsonPath("$.data.eventId").value(updatedReservation.event.id))
새로운 커밋에 올린내용입니다.
SuccessResponseDTO로 deserialize하여 SuccessResponseDTO 형식으로 테스트할수는 있으나
굳이 deserialize를 해서 테스트 해야하나라는 생각이 듭니다

```
 val response = result.response
        val objectMapper = ObjectMapper().registerModule(JavaTimeModule()).registerModule(KotlinModule())
        val successResponseDTO = objectMapper.readValue(response.contentAsString, SuccessResponseDTO::class.java)
        val data = objectMapper.convertValue(successResponseDTO.data, ReservationResponse::class.java)

        assertEquals(HttpStatus.CREATED.value(), result.response.status)
        assertEquals(MediaType.APPLICATION_JSON.toString(), result.response.contentType)
        assertEquals(sampleReservation.id, data.id)
        assertEquals(sampleReservation.user.id, data.userId)
        assertEquals(sampleReservation.event.id, data.eventId)
```

2023-10-08 13:30 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/controller/EventController.kt
> +        @PageableDefault(size = 10, sort = ["date", "id"]) pageable: Pageable
HTTP Query에 하나의 키로 두가지 값을 전달하는게 표준적인 행동인가요?

`sort_key`, `sort_by` 등으로 구분하는게 더 좋은것 같습니다 

그리고 기본은 `ID`, `DESC` 로 하는게 좋아보입니다

2023-10-08 13:32 UTC, junha-ahn commented
헤더 관련해서 당장 처리가 힘들다면, 일단 해당 Branch는 Page, Sort 관련해서만 진행했으면 좋겠습니다. (`feat/52-api-page-and-search`)

- 그리고 새로운 브랜치 `feat/52-restful-api-headers` 뭐 이런 이름으로 만들어서 작업하시는게 좋을것 같습니다.

위에서도 말했지만 현재 작업 내용이 너무 많습니다.

2023-10-08 14:04 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/controller/EventController.kt
> +        @PageableDefault(size = 10, sort = ["date", "id"]) pageable: Pageable
디스패쳐 서블릿에서 쿼리파라미터를 Pageable에 매핑할때의 표준 형식입니다

2023-10-08 14:05 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/controller/EventController.kt
> +        @PageableDefault(size = 10, sort = ["date", "id"]) pageable: Pageable
spring 표준구현체라는 말씀이시죠?

2023-10-08 14:12 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/controller/EventController.kt
> +        @PageableDefault(size = 10, sort = ["date", "id"]) pageable: Pageable
https://yoonbing9.tistory.com/38

https://velog.io/@dhk22/Spring-%EC%84%B8%EC%83%81-%EA%B0%84%EB%8B%A8%ED%95%9C-Pagination-Controller%EC%97%90%EC%84%9C-Pageable-%EA%B0%9D%EC%B2%B4-%EB%B0%9B%EC%95%84-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

페이징을 할때 저런식으로 요청하는것이 http 표준은 아닙니다.

저렇게 요청하면 굳이 쿼리파람 변수 여러개 만들필요없이
Pageable객체를 controller에서 바로 받을수있는거입니다

2023-10-09 14:26 UTC, minjun3021 commented on src/test/kotlin/com/group4/ticketingservice/filter/JwtAuthenticationFilterTest.kt
> -
원래 filter에서 response를 쓰는 방식이였는데 exceptionHadler에서 response를 작성하게 바뀌엇 삭제된 코드입니다 
머지 커밋에서 삭제 된듯하네요

2023-10-09 14:33 UTC, ParkJeongseop commented on src/main/kotlin/com/group4/ticketingservice/controller/BookmarkController.kt
> +        headers.set("Content-Location", "/bookmarks/%d".format(savedBookmark.id!!))
#112
해당내용 관련하여 새로 이슈 발행하였습니다. 현 PR에서는 종료하겠습니다.

2023-10-09 14:44 UTC, ParkJeongseop commented on src/main/kotlin/com/group4/ticketingservice/dto/ResponseDTO.kt
> +    val totalElements: Long? = null
#113 
해당 내용 관련하여 신규 이슈 발행하였습니다. 본 PR에서는 종료하겠습니다.

2023-10-09 14:47 UTC, junha-ahn commented on src/integrationTest/kotlin/com/group4/ticketingservice/Event/EventRepositoryTest.kt
> +        val specification = EventSpecifications.withTitle(title)
```sql
title LIKE "%코딩%"
```

과 같은 기능인가요?

2023-10-09 14:53 UTC, junha-ahn requested changes

2023-10-09 15:45 UTC, ParkJeongseop commented on src/integrationTest/kotlin/com/group4/ticketingservice/Event/EventRepositoryTest.kt
> +        val specification = EventSpecifications.withTitle(title)
-  API 문서에는 해당내용이 잘 포함되어있음을 확인하였습니다.
- 검색, 페이지네이션, 정렬 기능을 분리하여 테스트 추가하였습니다.

2023-10-09 15:57 UTC, minjun3021 commented on src/integrationTest/kotlin/com/group4/ticketingservice/Event/EventRepositoryTest.kt
> +        assertThat(result.content[4].title).isEqualTo(sampleEvents[2].title)
title기준으로 sort되었다는걸 알수있게
sampleEvents[4]->firstItem
sampleEvents[1]->secondItem
이런식으로 명식적으로 표현해주는게 좋을듯합니다.

왜 41032순서인지 안와닿네요

2023-10-09 16:01 UTC, junha-ahn requested changes
해당 Commit 에서 여러가지 테스트들이 전부 `paging with sorting` 또는

2023-10-09 16:01 UTC, junha-ahn commented on src/integrationTest/kotlin/com/group4/ticketingservice/Event/EventRepositoryTest.kt
> +    fun `EventRepository_findAll should return page of events with searching`() {
`EventRepository_findAll should return page of events with searching`
`EventRepository_findAll should return page of events with pagination` 

> 하나의 테스트 케이스는 단위 기능 중 하나의 시나리오만 테스트하라 - [링크](https://lxxjn0-dev.netlify.app/test-only-one-code-unit-at-a-time)

전부 분리하라고는 못하겠지만 해당 Commit에서 너무 한꺼번에 몰아넣은거 분리해주세요.

2023-10-09 16:04 UTC, ParkJeongseop commented on src/integrationTest/kotlin/com/group4/ticketingservice/Event/EventRepositoryTest.kt
> +    fun `EventRepository_findAll should return page of events with searching`() {
각각 검색과 페이지네이션, 정렬 모두 분리되어있습니다.

2023-10-09 16:05 UTC, ParkJeongseop commented on src/integrationTest/kotlin/com/group4/ticketingservice/Event/EventRepositoryTest.kt
> +        assertThat(result.content[4].title).isEqualTo(sampleEvents[2].title)
정렬된 인덱스 번호를 배열로 분리하여 코드 가독성을 향상시켰습니다.

2023-10-09 16:05 UTC, ParkJeongseop commented on docs/open-api.yaml
오류 수정하였습니다.

2023-10-09 16:08 UTC, merged