feat/126 check wait queue
f-lab-clone/ticketing-backend pull request #134
Opened 2023-10-30 15:11 UTC by minjun3021

#  What is this PR?
- Github Issue: #126 

# Key Changes
기존 Reserve 로직을 수정함

1. 요청을 받았을시 대기열에 유저가 해당 이벤트에대하여 
    대기열 티켓이 발행되었는지 확인후 발행 내역이 없다면 , 대기열 티켓 발행후 티켓 상태를 반환.

2. 요청을 받았을시 이전에 발행내역이 있지만 waiting상태라면 대기열 티켓 상태를 반환.

3. 요청을 받았을시 이전에 발행내역이있고 waiting이 상태가 아니라면 기존 Reserve로직 수행
    (이제서야 event 자원에 대하여 lock이 발생)

# Test Checklist

2023-10-30 23:22 UTC, junha-ahn requested changes

2023-10-30 23:22 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/service/ReservationService.kt
> +            waitingStatusResponse = restTemplate.exchange("$queueServerURL/$eventId/$userId", HttpMethod.GET, null, QueueResponseDTO::class.java).body
Issue 다시 확인해주세요. delete api입니다

2023-10-30 23:22 UTC, junha-ahn commented on src/integrationTest/resources/application.yml
> +      url: http://localhost:8082/ticket
이럴땐 어떻게 해야할까요? 

gitaction 에서 실행하는 환경엔 queue api가 없는데, 의존성을 어떻게해결할까요?

2023-11-01 05:36 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/service/ReservationService.kt
> +            waitingStatusResponse = restTemplate.exchange("$queueServerURL/$eventId/$userId", HttpMethod.GET, null, QueueResponseDTO::class.java).body
수정되었습니다

2023-11-01 05:37 UTC, minjun3021 commented on src/integrationTest/resources/application.yml
> +      url: http://localhost:8082/ticket
일단은 목업하여 테스트 하였습니다

2023-11-02 15:39 UTC, ParkJeongseop approved these changes
LGTM

2023-11-05 14:43 UTC, merged

2023-11-05 16:11 UTC, junha-ahn commented
```log
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:738)	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)	at java.base/java.lang.Thread.run(Thread.java:833)Caused by: java.net.ConnectException: Connection refused	at java.base/sun.nio.ch.Net.connect0(Native Method)	at java.base/sun.nio.ch.Net.connect(Net.java:579)	at java.base/sun.nio.ch.Net.connect(Net.java:568)	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)	at java.base/java.net.Socket.connect(Socket.java:633)	at java.base/java.net.Socket.connect(Socket.java:583)	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:246)	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:351)	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:373)	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:75)	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66)	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:862)	... 149 common frames omitted
```



위와 같은 에러가 나고 있습니다.