reservation feature and JPA init without test code
f-lab-clone/ticketing-backend pull request #24
Opened 2023-07-10 12:22 UTC by yunsuu

#  What is this PR?
- Github Issue: #3 

# Key Changes
- nothing now

# Test Checklist

2023-07-10 12:59 UTC, junha-ahn commented
향후 git issue

1. docker-compose - mysql - 을 사용해서 로컬 개발 환경 통일화 
2. controller - service - repository 패턴 적용과 함께 Test 구현 

**해당 PR에 대한 코드 리뷰 아닙니다**

2023-07-10 13:03 UTC, junha-ahn commented
개발팀 첫 :1st_place_medal:  기능 구현 PR 축하드립니다 :+1: :+1: :+1: 

매우 좋습니다 :)

2023-07-12 10:47 UTC, junha-ahn requested changes
check plz

2023-07-16 12:59 UTC, junha-ahn commented
@bohblue2 코드 리뷰 부탁드립니다 (프로젝트 구조 등)

2023-07-16 12:59 UTC, junha-ahn approved these changes

2023-07-16 13:00 UTC, junha-ahn commented
@yunsuu  테스트 시나리오 작성 및 테스트 코드 작성 부탁드립니다.

참고
- https://github.com/f-lab-clone/ticketing-service/pull/28

2023-07-16 13:49 UTC, bohblue2 commented
작은 수정사항들이 있습니다. 수정해주세요!

2023-07-16 13:54 UTC, bohblue2 requested changes
작은 수정사항이 있습니다. 수정해주세요.

2023-07-16 13:54 UTC, bohblue2 commented on src/main/kotlin/com/group4/ticketingservice/domain/Reservation.kt
> +)
패키지 이름이 domain이 아닌 entity로 변경해주세요. Github wiki의 `프로젝트 패키지 구조` 참조.

2023-07-16 13:54 UTC, bohblue2 commented on src/main/resources/application.properties
> +#spring.datasource.password=1234
필요하지 않은 주석은 제거해주세요.

Database의 계정 정보는 Plain text가 아닌 OS environment variable을 사용해주세요.

2023-07-16 13:54 UTC, bohblue2 commented on src/main/resources/application.properties
> +spring.datasource.password = ${OPENSHIFT_MYSQL_DB_PASSWORD}
OPENSHIFT 사의 데이터베이스를 이용하는 것을 안알려줘도 됩니다.

`MYSQL_DB_*` 형식으로 변경해주세요.

2023-07-16 13:54 UTC, bohblue2 commented on src/main/kotlin/com/group4/ticketingservice/controller/ReservationController.kt
> +    fun reservePerformance(@RequestBody user: Reservation): Reservation {
param이 user가 아니라 reservation으로 되는게 맞는 것 같아보입니다. 오타인가요?

2023-07-16 13:54 UTC, bohblue2 commented on build.gradle.kts
>          Qdomains.add("*.Q$qPattern*")
해당 부분 설명 부탁드립니다.

2023-07-16 15:38 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/domain/Reservation.kt
> +)
- [링크](https://github.com/f-lab-clone/ticketing-service/wiki/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%ED%8C%A8%ED%82%A4%EC%A7%80-%EA%B5%AC%EC%A1%B0)

2023-07-17 10:22 UTC, yunsuu commented on src/main/kotlin/com/group4/ticketingservice/controller/ReservationController.kt
> +    fun reservePerformance(@RequestBody user: Reservation): Reservation {
넵 오타입니당

2023-07-17 10:27 UTC, yunsuu commented on src/main/resources/application.properties
> +spring.datasource.password = ${OPENSHIFT_MYSQL_DB_PASSWORD}
적용하겠습니다.

2023-07-17 10:27 UTC, yunsuu commented on src/main/resources/application.properties
> +#spring.datasource.password=1234
적용하겠습니다.

2023-07-21 09:25 UTC, junha-ahn requested changes

2023-07-21 09:25 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/controller/ReservationController.kt
> +    fun reservePerformance(@RequestBody reservation: Reservation): Reservation {
향후에는 Reservation [DTO](https://github.com/f-lab-clone/ticketing-service/blob/main/src/main/kotlin/com/group4/ticketingservice/dto/BookmarkFromdto.kt)를 선언해서 사용해주세요
- 다만 현재 PR에서는, 돌아가는데 문제가 없기 때문에 **수정하지 않아도 됩니다**. (읽고 resolve 눌러주세요)

> 데이터 전송 객체(DTO)란 프로세스 사이에서 데이터를 전송하는 객체를 말합니다. DTO 기법을 사용하면 중요한 정보를 노출시키지 않고 두 시스템간.. - [from](https://www.okta.com/kr/identity-101/dto/)

2023-07-21 09:25 UTC, junha-ahn commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:mysql://localhost:3306/test
주석 삭제 부탁드립니다 
- [환경변수 주입 방법](https://velog.io/@crow/Spring-boot-%EC%99%B8%EB%B6%80-%ED%99%98%EA%B2%BD%EB%B3%80%EC%88%98-%EC%A3%BC%EC%9E%85)을 사용하시면 편하게 사용 가능합니다.

2023-07-21 09:25 UTC, junha-ahn commented on src/test/kotlin/com/group4/ticketingservice/ReservationJpaTest.kt
> +        if(savedReservation != null){
테스트 코드에는 조건문이 없어야 합니다! 

```kotlin
val savedReservation = reservationRepository.save(reservation)
val foundReservation = reservationRepository.findByUserId(1)

Assertions.assertNotNull(foundReservation)
Asserts.assertEquals(savedReservation.id, foundReservation.id)
```

으로 수정하는게 좋을 것 같습니다.

또한 코틀린 문법에 따르면 `object?.key` 도 사용가능할듯합니다
```kotlin
Asserts.assertEquals(savedReservation.id, foundReservation?.id)
```

2023-07-21 09:25 UTC, junha-ahn commented on src/test/kotlin/com/group4/ticketingservice/ReservationJpaTest.kt
### 1. 레이어별 테스트

해당 테스트는 Repository - Database간의 상호작용을 테스트 하였습니다.

Controller의 테스트가 필요해보입니다. [관련개념글](https://github.com/HomoEfficio/dev-tips/blob/master/Spring-Boot-%EB%A0%88%EC%9D%B4%EC%96%B4%EB%B3%84-%ED%85%8C%EC%8A%A4%ED%8A%B8.md)

[컨트롤러 테스트 코드 Example](https://github.com/f-lab-clone/ticketing-service/blob/main/src/test/kotlin/com/group4/ticketingservice/bookmark/BookmarkControllerTest.kt)


### 2. 테스트 환경 격리
해당 테스트 Local 환경에 실제로 구동중인 MySQL에 의존하고 있습니다. 
따라서 Git actions를 통해 [test](https://github.com/f-lab-clone/ticketing-service/actions/runs/5620294530/job/15228947584?pr=24) 할때는 동일한 환경이 아니기 때문에 실패하게 됩니다. (MySQL이 준비되어 있지 않기 때문에)

> 격리된 테스트 (Isolated Test) 데이터베이스와 같은 공유 자원을 사용하는 테스트는 실행 순서에 따라 성공, 실패 여부가 결정되는 비결정적인(non-deterministic) 테스트가 될 수 있다. 이런 비결정적 테스트는 실패하면 버그가 원인인지, 비결정적 동작이 원인인지 알기 힘들다. 따라서 테스트는 실행 순서에 상관 없이 독립적으로, 결정적(deterministic)으로 실행되어야한다. 테스트 격리는 공유 자원을 사용하는 여러 테스트끼리 격리하여 서로 영향을 주고 받지 못하게 하는 기법이다. 특히 데이터베이스를 사용하는 객체를 테스트할 때 테스트 격리가 필요하다. - [from](https://hudi.blog/isolated-test/)

해결 방법은 몇가지가 있습니다.
1. in-memory Database H2를 사용하여 테스트
2. testcontainer 환경에서 (현재 main branch에 준비되어 있습니다) 해당 코드를 테스트 하기 
3. 해당 Database 테스트는 본질적으로 Unit Test가 아니기에 해당 파일 삭제하기

먼저 1번의 경우 좋은 방법이 아닙니다. 왜냐하면 h2는 mysql 을 mock up(가짜화)하는데 성공해 유닛 테스트를 구현할 수 있게는 해주지만, 본질적으로 mysql이 아니기 때문에 실제와 같은 환경을 제공해주지는 않기 때문입니다. 
따라서, 2번이 더 좋은 선택이라고 볼 수 있습니다 - [관련 글](https://medium.com/riiid-teamblog-kr/testcontainer-%EB%A1%9C-%EB%A9%B1%EB%93%B1%EC%84%B1%EC%9E%88%EB%8A%94-integration-test-%ED%99%98%EA%B2%BD-%EA%B5%AC%EC%B6%95%ED%95%98%EA%B8%B0-4a6287551a31)

2023-07-21 15:09 UTC, junha-ahn commented
통합 테스트 관련 오류 이슈 #48

2023-08-08 15:52 UTC, closed without merging