Feature/4 user register
f-lab-clone/ticketing-backend pull request #30
Opened 2023-07-12 15:07 UTC by minjun3021

#  What is this PR?
- Github Issue:

# Key Changes

# Test Checklist

2023-07-12 16:07 UTC, junha-ahn requested changes
코틀린 스프링부트에 관한 내용이 많아서 보기 어려운것들은 패스하고, 아는 한에서 열심히 댓글 달아봤습니다 :)

2023-07-12 16:07 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/service/impl/UserServiceImpl.kt
> +                ?:throw IllegalArgumentException("아이디 또는 패스워드가 일치하지 않습니다.")
저 같은 경우에 Password가 일치하지 않으면 404를 던질것 같습니다 (보안관점) 
- https://github.com/nsarno/knock/issues/44

2023-07-16 06:02 UTC, bohblue2 commented on src/main/kotlin/com/group4/ticketingservice/controller/UserController.kt
> +data class SignUpRequest(
DTO 파일로 이동하는게 좋은것같습니다.

2023-07-16 14:44 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/service/UserDetailService.kt
> +class UserDetailService(private val userRepository: UserRepository) :
UserService는 자체적으로 유저를 관리하기 위하여 만든 서비스이고
UserDetailsService는 Spring Security가 사용자 인증 과정에서 사용자의 정보를 가져오는 방법을 정의하는 인터페이스입니다.
Spring security에서 정의한 인터페이스이고, 구현체가 UserDetailService인겁니다.

2023-07-16 14:48 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/controller/UserController.kt
> +data class SignUpRequest(
알겠습니다

2023-07-16 15:14 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/service/impl/UserServiceImpl.kt
> +class UserServiceImpl(private val userRepository: UserRepository,
이전에 했던 프로젝트에서 인터페이스에 대하여 2개의 구현체를 만든적이 있었습니다 (ex. 비밀번호 변경) .
그리고 서칭하면서 봤던 구조들이 이런식으로 구현되어있었는데 @Transaction 을 쓸려면 이런 구조로 만들어야 한다는데
spring 특정 버전부터 필요가 없다고 하네요 . 인터페이스는 없에고 서비스 구현하겠습니다.

2023-07-16 15:23 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/service/impl/UserServiceImpl.kt
> +                ?:throw IllegalArgumentException("아이디 또는 패스워드가 일치하지 않습니다.")
controller단에서 IllegalArgumentException를 catch하여 401을 던지고 있습니다

2023-07-16 15:28 UTC, junha-ahn commented
Todo
- [ ] 가장 최신의 Main branch에 내용을 Merge 받아와주세요
- [ ] 브랜치 이름 변경 [rule](https://github.com/f-lab-clone/ticketing-service/wiki/Convention#branch-rule)

2023-07-16 15:34 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/entity/User.kt
> +@Table(name = "users")
단수로 변경하겠습니다

2023-07-16 15:43 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/TicketingserviceApplication.kt
> +@EnableJpaAuditing
JPA를 사용하므로 생성일자를 Entiy에서 관리하는것이 객체 지향적인 모델링에 더 부합합니다

2023-07-17 11:55 UTC, junha-ahn requested changes

2023-07-17 13:20 UTC, junha-ahn commented
참고: [Spring Security가 적용된 곳을 효율적으로 테스트하자.](https://tecoble.techcourse.co.kr/post/2020-09-30-spring-security-test/)

2023-07-17 13:49 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/service/impl/UserServiceImpl.kt
> +                ?:throw IllegalArgumentException("아이디 또는 패스워드가 일치하지 않습니다.")
예 맞습니다 제가 첫번째 코멘트를 잘못이해했었네요.
1번 2번 케이스를 다 포함하는 문법입니다

findbyEmail 식의 결과가 NULL이라면
엘비스 연산자(?:)에 의하여 엘비스 연산자 오른쪽 식(throw exception)이 결과값이 됩니다.

findbyEmail식의 결과가 정상적인 값이라면
안전 호출(?.)에 의하여 takeIf함수가 실행되는데
takeIf함수는 조건식인 매개변수로 넣어준 람다 함수를 만족하지 않으면 NULL을 던지는데 
그렇게 되면 엘비스 연산자에 따라서 throw exception을 하게 됩니다.

2023-07-28 09:11 UTC, junha-ahn requested changes
테스트코드 작성 파이팅!

2023-07-28 09:11 UTC, junha-ahn commented on build.gradle.kts
> +    implementation("org.json:json:20230227")
[참고](https://github.com/f-lab-clone/ticketing-service/wiki/Convention#deserializer)해서 GSon사용해주세요

2023-07-28 09:11 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/JwtAuthorizationEntryPoint.kt
> +class JwtAuthorizationEntryPoint : AuthenticationEntryPoint {
Mismatch 이유가 있나요
- JwtAuthorizationEntryPoint, AuthenticationEntryPoint

2023-07-28 09:11 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/controller/UserController.kt
> +    @GetMapping("/username")
[kakao](https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#get-token-info) 등을 참고하여 변경해주세요.

목적 
1. 프론트에서 로그인 확인용 API로 활용 (예시: 상단 메뉴바에서 로그인/로그아웃 중 어떤 버튼을 노출할지 결정하는 등)
2. Test Code에서 활용
3. 추후 refresh 기능 추가 (또는 별도 API로 refresh)

2023-07-28 09:11 UTC, junha-ahn commented on .gitignore
> +src/main/resources/application-dev.properties
gitignore에서 일단 삭제 부탁드립니다.

2023-07-31 08:52 UTC, junha-ahn requested changes
## 유닛 테스트 / 통합 테스트

SignIn, GetAceessToken 테스트는 그대로 Integration 에서 진행하고
CreateUser에 대한 Controller Test는 `src/test/` 밑으로 옮기면 될것 같습니다.
필요없어진 `TestUserDetailService`는 삭제 부탁드립니다.

의견
- Fake Object `TestUserDetailService` 의 관리가 점점 부담으로 다가올 것으로 예상
- 각 테스트 단위로 메서드를 쉽게 Mock up할 수 있지만 Fake Object는 input에 대한 조건문을 구현해야하는 복잡성
- createUser는 **spring security 관련 의존성이 없으니** 슬라이스 테스트(`src/test/...`) 진행

2023-07-31 08:52 UTC, junha-ahn commented on src/test/kotlin/com/group4/ticketingservice/user/UserControllerTest.kt
> +    fun `GET_api_users_username should return username injected by Spring Security with HTTP 200 OK`() {
API url과 일치 부탁드립니다.

2023-07-31 08:52 UTC, junha-ahn commented on src/integrationTest/kotlin/com/group4/ticketingservice/User/UserControllerTest.kt
> +import org.json.JSONObject
GSON 이용 부탁드립니다. [참고](https://github.com/f-lab-clone/ticketing-service/wiki/Convention#deserializer)

2023-07-31 08:52 UTC, junha-ahn commented on src/integrationTest/kotlin/com/group4/ticketingservice/User/UserControllerTest.kt
> +    fun `signUp Success Test`() {
테스트명 문장형으로 부탁드립니다.

2023-07-31 08:52 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/controller/UserController.kt
> +    @PostMapping
회원가입 => users/signup
로그인 => users/signin

참고: [sign up vs register](https://www.quora.com/What-is-the-difference-between-a-sign-up-form-and-a-register-form-in-HTML), [sign in vs login](https://chaeyeon-chaeyeon.tistory.com/66)

2023-07-31 08:52 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/service/UserService.kt
> +                password = encoder.encode(request.password),
Service Layer에서 해시 관련 테스트 부탁드립니다.
- createUser 호출 후 User의 password는 encrypted 되어있어야 한다.

2023-07-31 08:52 UTC, junha-ahn commented on src/test/kotlin/com/group4/ticketingservice/bookmark/BookmarkControllerTest.kt
> +    @WithMockUser(roles = ["USER"])
아직 로그인 관련 권한 체크 필요없습니다.

2023-07-31 13:49 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/JwtAuthorizationEntryPoint.kt
> +class JwtAuthorizationEntryPoint : AuthenticationEntryPoint {
class JwtAuthorizationFilter : BasicAuthenticationFilter구조로 있습니다.
원래는 httpBasic요청에 대한 인증 처리를 하는 필터인 BasicAuthenticationFilter를 오버라이드를 하여
jwt인가과정에 맞게 바꾸었고, BasicAuthenticationFilter가 AuthenticationEntryPoint 를 요구하여 어쩔수없습니다

2023-07-31 23:29 UTC, junha-ahn requested changes
`KtFormat` 돌려 주세요! 이제 끝이네요! 굳입니다 :+1:

2023-07-31 23:29 UTC, junha-ahn commented on src/integrationTest/kotlin/com/group4/ticketingservice/User/UserControllerTest.kt
> +    fun `POST_api_users_login should return HTTPStatus 400 BAD_REQUEST when password is invalid`() {
username, password 오류 401 반환 부탁드립니다. [참고](https://stackoverflow.com/questions/32752578/whats-the-appropriate-http-status-code-to-return-if-a-user-tries-logging-in-wit)

2023-07-31 23:29 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/TicketingserviceApplication.kt
> +import org.springframework.data.jpa.repository.config.EnableJpaRepositories
사용안하는 패키지 삭제 부탁드립니다.

2023-07-31 23:29 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/config/Config.kt
> +import org.springframework.security.config.annotation.web.builders.HttpSecurity
사용안하는 패키지 삭제 부탁드립니다

2023-07-31 23:29 UTC, junha-ahn commented on src/main/resources/application.properties
> +ticketing.jwt.issuer=minjun
전체 ENV 사용 부탁드립니다.
다만 주석으로 아래 예시값 달아놓는게 좋을것 같습니다

 ```bash
ticketing.jwt.secret=${...}
ticketing.jwt.expiration=${...}
ticketing.jwt.issuer=${...}
# ticketing.jwt.secret=d2VhcmVuYXZ5c3dkZXZlbG9wZXJzLmFuZGlhbW1pbmp1bjMwMjE=
# - base64 string reference : https://springdoc... 
# ticketing.jwt.expiration-hours=24
# ticketing.jwt.issuer=ticketing-backend
```

2023-07-31 23:29 UTC, junha-ahn commented on src/test/resources/application.properties
> +spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
Test에서는 DB 정보 필요 없지 않나요? 확인 후 삭제 부탁드립니다.

2023-08-01 08:00 UTC, merged