Feat/39 컨벤션 정의: Time
f-lab-clone/ticketing-backend pull request #55
Opened 2023-07-23 10:28 UTC by bohblue2

#  What is this PR?
- Github Issue: #39 

# Key Changes
- WIP: Implement ClockFactory
- Implement test code for util/DateTimeConverter

# Test Checklist
None

2023-07-23 10:41 UTC, junha-ahn requested changes
git actiosn test 실패했습니다 확인해주세요

그리고 이슈에 있는 테스트 리스트 최대한 구현할려고 노력해주세요.

2023-07-23 10:41 UTC, junha-ahn commented on src/test/kotlin/com/group4/ticketingservice/util/ClockFactoryTest.kt
> +        assert(clockFactory.now().year == 3332)
year 부터 second까지 테스트 되었으면 좋겠습니다.

2023-07-23 10:41 UTC, junha-ahn commented on src/test/kotlin/com/group4/ticketingservice/util/DateTimeConverterTest.kt
> +    fun serialize() {
테스트명 더 명확하게 명시해주세요.

2023-07-31 23:51 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/service/BookingService.kt
> +    private val clock: Clock
이렇게 주입하는 경우 Clock의 config timezone은 UTC로 세팅되는건가요?

2023-07-31 23:51 UTC, junha-ahn commented on src/test/resources/application.properties
> +time-travel.zone=UTC
UTC는 환경변수에서 주입안하고, clockConfig에서 고정해서 사용해도 괜찮지 않을까요?

2023-07-31 23:51 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/dto/BookingDto.kt
> +    val bookedAt: OffsetDateTime
DTO에 `OffsetDateTime` 을 사용하셨는데 이 경우 어떻게 데이터가 처리됩니까?

1. ISO String 을 넣어서 생성했을때
2. ISO가 아닌 String을 넣어서 생성했을때 

2번의 경우 에러가 나면 좋겠...지만 그렇진 않겠죠? 그런 방법 없을까요?
-  향후 Validation에서 다 처리해주지 않아도 뭔가 방법이 없을까요? 넵

2023-08-03 10:12 UTC, bohblue2 commented on src/main/kotlin/com/group4/ticketingservice/service/BookingService.kt
> +    private val clock: Clock
네

2023-08-03 10:13 UTC, bohblue2 commented on src/test/resources/application.properties
> +time-travel.zone=UTC
명시적으로 application.properties에 표현하면 더 좋을것 같습니다.

2023-08-03 10:15 UTC, bohblue2 commented on src/main/kotlin/com/group4/ticketingservice/dto/BookingDto.kt
> +    val bookedAt: OffsetDateTime
1. 정상적인 ISO8601 문자열(2000-01-01T00:00:00+00:00)을 넣으면 정상적으로 파싱됩니다.

2. 오프셋 정보(+00:00)가 없을 경우 파싱시 InvalidationArgument에러가 발생합니다.

2023-08-03 10:17 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/dto/BookingDto.kt
> +    val bookedAt: OffsetDateTime
테스트로 구현해주세요!

2023-08-03 10:18 UTC, junha-ahn commented on src/test/resources/application.properties
> +time-travel.zone=UTC
제가 생각하는건 개발자의 실수로 UTC 명사가 빠진 경우가 문제를 발생시키고, UTC외에는 존재하지 않으니 필요치 않은 config화라고 생각합니다.

2023-08-04 11:52 UTC, bohblue2 commented on src/main/kotlin/com/group4/ticketingservice/dto/BookingDto.kt
> +    val bookedAt: OffsetDateTime
파싱을 실패하면 java.time 에서 자동으로 오류를 throw 합니다.

2023-08-04 12:32 UTC, junha-ahn requested changes
@minjun3021 님의 요청으로 내일 이 PR 관련으로 간단 발표 부탁드립니다. 
- 어떤 작업을 했는지, 코드 레벨에서 어떤 영향을 주는지
- 또한 Wiki 에 관련 Time rule/사용법 에 대해서도 업데이트 부탁드립니다.

2023-08-04 12:32 UTC, junha-ahn commented on src/integrationTest/kotlin/com/group4/ticketingservice/booking/BookingRepositoryTest.kt
> +            bookedAt = OffsetDateTime.now(clock)
단위 테스트는 하나의 테스트에 집중해주세요 (또한 해당 테스트는 Time관련된 이름으로 파일을 만들어서 분리하는게 어떨까요?)

또한 SamplePerformance 객체를 만들때 위와 같이 OffsetDatetime객체를 직접 만드는게 아니라, ISOString 형식의 문자열로 farsing해서 주입해보는 형식의 **테스트 추가** 가능합니까?? (실제 HTTP Request같이)

관련 PR comment - https://github.com/f-lab-clone/ticketing-backend/pull/28#discussion_r1267810719

2023-08-04 12:32 UTC, junha-ahn commented on src/test/kotlin/com/group4/ticketingservice/booking/BookingControllerTest.kt
> +        bookingStartTime = OffsetDateTime.now(clock) + Duration.ofHours(1),
1. 위 하나의 테스트 Rule을 지켜주세요
2. 또한 OffsetString 형식으로 변경가능합니까? (위 코멘트와 동일)

2023-08-04 14:39 UTC, junha-ahn requested changes

2023-08-04 14:39 UTC, junha-ahn commented on src/integrationTest/kotlin/com/group4/ticketingservice/booking/BookingE2ETest.kt
1. `BookingE2ETest`는 필요 없습니다. Controller Unit 테스트에서 이미 테스트가 끝난 부분을 굳이 재 구현할 필요가 없다고 생각됩니다.
2. 제가 위에서 말했던건, TimeE2ETest 입니다.
- TimeE2ETest File 생성 (해당 파일을 TimeE2E Test로 작성하는 이유는 해당 파일의 목적은 "ISO String" 을 입력하고 Database와의 상호작용을 보는것이 목적이지, Booking 등의 로직을 확인하는게 아닙니다)
- ISOString을 `POST /bookings` Request Param에 포함시켜 테스트 (기존에 UnitTest에서 작성하진 로직을 여기서 구현해달라는 의미였습니다)
3. 따라서 해당 파일 삭제 후 위에 언급된 테스트만 구현 부탁드립니다.

2023-08-04 14:39 UTC, junha-ahn commented on src/integrationTest/kotlin/com/group4/ticketingservice/booking/BookingRepositoryTest.kt
> +            bookingStartTime = OffsetDateTime.now() + ofHours(1),
해당 테스트의 이름은 `OffsetDatetime only parse to NO-OFFSET-UTC time` 정도가 적당한거 아닙니까?

2023-08-04 16:06 UTC, junha-ahn requested changes

2023-08-04 16:06 UTC, junha-ahn commented on src/integrationTest/kotlin/com/group4/ticketingservice/TimeE2ETest.kt
> +                )
`fromJSON`이 아니라 `response.bookingStartTime`, `bookingEndTime` 도  ISOString으로 비교 부탁드립니다.

2023-08-04 16:06 UTC, junha-ahn commented on src/integrationTest/kotlin/com/group4/ticketingservice/booking/BookingRepositoryTest.kt
> +            bookingStartTime = OffsetDateTime.now() + ofHours(1),
제가 `OffsetDateTime.now() + ofHours(2)`  로직에 대한 이해가 없어서 그런지 몰라도 test name만 보고는 잘 이해가 안갑니다. 

`without OffsetDateTime` 인데 왜 samplePerformance에 OffsetDatetime을 다루는 로직이 들어가있는지 이해가 안갑니다.

답변 부탁드립니다.

2023-08-05 06:24 UTC, bohblue2 commented on src/integrationTest/kotlin/com/group4/ticketingservice/TimeE2ETest.kt
> +                )
수정했습니다.

2023-08-05 07:02 UTC, junha-ahn requested changes

2023-08-05 07:02 UTC, junha-ahn commented on src/integrationTest/kotlin/com/group4/ticketingservice/TimeE2ETest.kt
> +    fun `POST performances with json plain text should return performance`() {
좋습니다! 다만 테스트명이 불명확한다고 생각됩니다. 
- 물런 `return performance`를 하고 있습니다. (그것도 테스트 내용이기는 합니다)
- 하지만, 주 목적은 `COVERT UTC`라고 생각됩니다.
- `API  only returns time in UTC without any offset` 정도의 제목이 어떻습니까?

### WHEN:
- api 요청
- OFFSET이 포함된 시간 정보 포함

### THEN:
- API는 정상적으로 응답(200 OK)합니다.
- 응답은 UTC로 변환
- date: "2022-09-01T12:00:00.001Z"

2023-08-05 07:32 UTC, merged