Feat/40 validation
f-lab-clone/ticketing-backend pull request #59
Opened 2023-08-04 15:15 UTC by minjun3021

#  What is this PR?
- Git Issue: #40 

Validate에 실패하면 throw하는 MethodArgumentNotValidException를  globalExceptionHandler가 캐치하여 
500이 아닌 400에러와 validate 에 실패한사유를  message로 보내준다.

# Key Changes

# Test Checklist

2023-08-04 15:20 UTC, junha-ahn requested changes

2023-08-04 15:24 UTC, junha-ahn requested changes

2023-08-04 15:24 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/GlobalExceptionHandler.kt
> +        val errorDto = ErrorResponseDto(errorCode = "${ HttpStatus.BAD_REQUEST}", message = exception.bindingResult.allErrors[0].defaultMessage+" 형식에 맞게 다시 시도하십시오.")
해당 에러 메세지 형식은 프론트엔드 개발자를 힘들게 합니다.

message는 위와 같은 형식을 사용해도 문제 없지만, 나머지 `allErrors` 결과도 한번에 프론트로 넘겨줄 필요도 있습니다. 

```javascript
{
  message: '', // 그대로 유지
  errors: allErrors, // errors를 키로할지는 고민 부탁드립니다.
} 
```
참고
- https://github.com/f-lab-clone/ticketing-backend/issues/36#issuecomment-1646807369
- [카카오 Error Code](https://shopping-developers.kakao.com/hc/ko/articles/4578818403343-%EC%9D%91%EB%8B%B5-%EC%BD%94%EB%93%9C-%EB%B0%8F-%EC%97%90%EB%9F%AC-%EC%BD%94%EB%93%9C) - "6) 상품 Validation 에러 메시지 샘플" 참고

2023-08-05 04:14 UTC, junha-ahn commented
혹시 `application/json` 형식만 요청 허용하도록 하는것도 가능합니까?

2023-08-05 07:04 UTC, minjun3021 commented
@junha-ahn @RequestBody 어노테이션이 JSON이 아니면 다 거릅니다

2023-08-05 07:31 UTC, junha-ahn requested changes

2023-08-05 07:31 UTC, junha-ahn commented on src/test/kotlin/com/group4/ticketingservice/user/UserControllerTest.kt
> +        resultActions.andExpect(MockMvcResultMatchers.status().isBadRequest)
중요하게 체크해야하는 포인트가 두개 있다고 생각됩니다.

1. name, email, password 등의 에러를 뿜어내는것
2. errors 키를 통해 해당 형식을 뿜어내는 것 

아래와 같은 형식으로 부탁드립니다.
```
.andExpect(jsonPath("$.errors[0]").value("...")
.andExpect(jsonPath("$.errors[1]").value("...")
.andExpect(jsonPath("$.errors[2]").value("...")
```

2023-08-05 07:38 UTC, minjun3021 commented on src/test/kotlin/com/group4/ticketingservice/user/UserControllerTest.kt
> +        resultActions.andExpect(MockMvcResultMatchers.status().isBadRequest)
{
    "errorCode": "400 BAD_REQUEST",
    "errors": [
        "[password](은)는 크기가 9에서 128 사이여야 합니다  ||  입력된 값: [1234567]",
        "[name](은)는 크기가 2에서 30 사이여야 합니다  ||  입력된 값: [김]",
        "[email](은)는 올바른 형식의 이메일 주소여야 합니다  ||  입력된 값: [qw]"
    ]
}

{
    "errorCode": "400 BAD_REQUEST",
    "errors": [
        "[name](은)는 크기가 2에서 30 사이여야 합니다  ||  입력된 값: [김]",
        "[password](은)는 크기가 9에서 128 사이여야 합니다  ||  입력된 값: [1234567]",
        "[email](은)는 올바른 형식의 이메일 주소여야 합니다  ||  입력된 값: [qw]"
    ]
}
그렇게 못한이유가있습니다 똑같이 요청을 보냈는데 순서가 다릅니다

2023-08-05 07:42 UTC, junha-ahn commented on src/test/kotlin/com/group4/ticketingservice/user/UserControllerTest.kt
> +        resultActions.andExpect(MockMvcResultMatchers.status().isBadRequest)
1. `.value(...)` => `.isString()`, `.isNotNull()`
2. `.andExpect(jsonPath("$.errors").isLength(3))`

이런 방법 없나요?

2023-08-05 10:14 UTC, merged