Feat/57 test coverage 80
f-lab-clone/ticketing-backend pull request #63
Opened 2023-08-08 11:33 UTC by minjun3021

#  What is this PR?
coverage verification rule을 전체 커버리지 80%로 변경하였고
빠져있던 테스트 케이스를 추가

# Key Changes

# Test Checklist

2023-08-08 12:27 UTC, junha-ahn commented on build.gradle.kts
> +                counter = "INSTRUCTION"
BRANCH, LINE과 INSTRUCTION의 차이는 무엇인가요? 

혹시 INSTRUCTION을 택하신 이유가 있나요

2023-08-08 13:15 UTC, minjun3021 commented on build.gradle.kts
> +                counter = "INSTRUCTION"
위에 3가지 옵션은 coverage verification을 검토하는 기준인데
LINE: 말그대로 코드가 몇줄인지
BRANCH: if문이나 switch같은 조건문,분기문에서  생길수있는 경우의수
(ex. 클래스 파일에 if문이 1개인데 if 의 true,false 2가지 경우중 true만 테스트했으면 test coverage 50%)
INSTRUCTION: java 바이트코드 명령수

BRANCH가  적합해보일수도있지만 
코틀린의 ?:(Elvis Operation) 문법을 사용한다면 2가지 분기를 테스트 하기 어려운구조가 만들어집니다

test의 기준으로 INSTRUCTION이 가장 어울립니다.

2023-08-08 13:21 UTC, junha-ahn commented on build.gradle.kts
> +                counter = "INSTRUCTION"
개인적으로는 BRANCH, INSTRUCTION 두가지 모두 사용하는게 좋을것 같습니다. 

<br/> 

>?:연산자를 if문으로 바꾸는 방법도있지만 test coverage를 상승시키려고 프로젝트에 코드를 수정하는건 좋은 의도가 아닙니다.

해당 PR에서 `?` 연산자를 `if` 문으로 변경하신거 아닌가요?

2023-08-08 13:22 UTC, minjun3021 commented on build.gradle.kts
> +                counter = "INSTRUCTION"
착오가 있었습니다 ?연산자 말고 ?:였습니다

2023-08-08 13:22 UTC, minjun3021 commented on build.gradle.kts
> +                counter = "INSTRUCTION"
수정한코드는 의미없게 되었습니다

2023-08-08 15:15 UTC, junha-ahn reviewed
Branch 를 현재 50%로 맞추고 Merge하는건 어떨까요?

2023-08-08 16:11 UTC, minjun3021 commented
instruction : 86%
branch : 67%
까지 상승시켰습니다

branch coverage limit 60%설정 하였습니다

2023-08-08 16:37 UTC, junha-ahn approved these changes
LGTM

2023-08-09 03:00 UTC, junha-ahn requested changes

2023-08-09 13:51 UTC, junha-ahn approved these changes

2023-08-09 14:47 UTC, ParkJeongseop commented on src/test/kotlin/com/group4/ticketingservice/filter/JwtAuthorizationEntryPonitTest.kt
> +        assertEquals(HttpServletResponse.SC_UNAUTHORIZED, res.status)
여기도 ```// then``` 해주세요.

2023-08-09 15:07 UTC, junha-ahn commented on src/test/kotlin/com/group4/ticketingservice/filter/JwtAuthenticationFilterTest.kt
> +        assertThrows(BadCredentialsException::class.java) {
given when then 붙이는거 권장하더군요 좋습니다

아래와 같은 테스트 라이브러리들도 있고요
```java
.when(this.todoRepository.save(any(TodoEntity.class)))
                .then(AdditionalAnswers.returnsFirstArg()); 

```

2023-08-10 02:52 UTC, merged