feat/59-implement-reservation-system
f-lab-clone/ticketing-backend pull request #79
Opened 2023-09-02 14:47 UTC by bohblue2

#  What is this PR?
- Github Issue:

# Key Changes

# Test Checklist

2023-09-08 13:36 UTC, junha-ahn requested changes

2023-09-08 13:36 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/entity/Event.kt
> +    var eventStartTime: OffsetDateTime,
https://github.com/f-lab-clone/ticketing-backend/issues/53#issuecomment-1702763820 에 나와있는데로 작업 부탁드립니다.

`event_start_time` => `start_time` 굳이 event라는 이름을 다시 사용할 필요 없어보입니다. endtime도 마찬가지입니다.

2023-09-08 13:37 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/entity/Event.kt
> +    var eventStartTime: OffsetDateTime,
그리고 메인 브랜치 머지한번 부탁드립니다. (Generate OpenAPI docs 오류 수정 )

2023-09-10 15:31 UTC, bohblue2 commented on src/main/kotlin/com/group4/ticketingservice/entity/Event.kt
> +    var eventStartTime: OffsetDateTime,
메인에서 땡겼는데 안되내요.

2023-09-10 15:38 UTC, bohblue2 commented on src/main/kotlin/com/group4/ticketingservice/entity/Event.kt
> +    var eventStartTime: OffsetDateTime,
해결

2023-10-09 09:52 UTC, closed without merging