Feat/39 time convention
f-lab-clone/ticketing-backend pull request #90
Opened 2023-09-18 16:50 UTC by minjun3021

#  What is this PR?
- Github Issue: #39 

# Key Changes

- JVM의 TimeZone을 설정
- DB의 serverTimezone을 UTC로 설정
- OffsetDateTime을 사용 

위의 작업을 함으로써 #55에서 
request를 parse할때 UTC시간으로 컨버트하는 작업을
디비에 저장될때 자동으로 되게함

OffsetDateTime을 사용함으로
시간관련 요청의 형식은

2023-09-19T00:46:00+09:00
2023-09-18T15:46:00Z

이런식으로 할수있음
# Test Checklist

2023-09-18 16:56 UTC, minjun3021 commented
![request 예시](https://github.com/f-lab-clone/ticketing-backend/assets/33713012/bc4ad6f0-8058-4251-a371-ca1c54fc9759)

같은시각을
UTC+00:00인 시간과
UTC+00:00이 아닌 시간을 요청보내도 
DB에 일관되게 저장되는 모습

 *reservationStartTime,reservationEndTime 필드 참고

2023-09-18 17:02 UTC, minjun3021 commented
![integration test](https://github.com/f-lab-clone/ticketing-backend/assets/33713012/2d7f7e6f-ead0-48a1-9706-2c16f6cb72f6)

기존 time 관련 테스트도 통과

2023-09-19 01:51 UTC, junha-ahn requested changes
매우 좋습니다!!!

2023-09-19 01:51 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/config/TimeZoneConfig.kt
> +        TimeZone.setDefault(TimeZone.getTimeZone("UTC"))
`src/main/.../TicketingserviceApplication.kt` 에도 같은 코드가 있는데 둘이 각각 필요한건가요?

2023-09-19 01:51 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/controller/EventController.kt
> +    fun createEvent(@RequestBody request: EventCreateRequest): ResponseEntity<EventResponse> {
주석으로 TimeE2E 테스트를 위한 임시 API라고 남기는게 좋을것 같습니다.

2023-09-19 01:51 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/dto/UserDto.kt
> +    val createdAt: OffsetDateTime?
JPA 설정으로 `createdAt`, `updatedAt` 자동 생성할 수 있는거 아니였나요?
- `BaseTimeEntity.kt` 도 있는데 왜 `createdAt`을 직접 만드는걸까요?

2023-09-19 09:22 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/config/TimeZoneConfig.kt
> +        TimeZone.setDefault(TimeZone.getTimeZone("UTC"))
TicketingserviceApplication.kt에 있는 코드는 실수로 남겨져있는 코드입니다 
없어질 예정 입니다

2023-09-19 09:22 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/controller/EventController.kt
> +    fun createEvent(@RequestBody request: EventCreateRequest): ResponseEntity<EventResponse> {
네

2023-09-19 09:23 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/dto/UserDto.kt
> +    val createdAt: OffsetDateTime?
CreateAt을 직접 만드는것이 아닌 
User의 Entity를 클라이언트에 돌려줄때 
사용되는 DTO에 필드중하나가 createAT입니다.

자동 생성되는 createdAt을 dto에 담아서 보여주는겁니다. 햇갈리신듯 하네요

2023-09-19 09:26 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/dto/UserDto.kt
> +    val createdAt: OffsetDateTime?
아 Dto였군요.

2023-09-19 09:32 UTC, merged