feat/36 custom error handling
f-lab-clone/ticketing-backend pull request #91
Opened 2023-09-19 11:01 UTC by minjun3021

#  What is this PR?
- Github Issue: #36 

# Key Changes

미리 예상할수있는 에러를 ErrorCodes EUM class에 정의해놓고
문제가 있는곳에서 직접만든 CustomException을 ErroCodes와 함께 던지고
ExceptionHandler가 CustomException을 잡아서 처리한다 .

# Test Checklist

2023-09-19 11:02 UTC, minjun3021 commented
![ErrorResponse 형식](https://github.com/f-lab-clone/ticketing-backend/assets/33713012/df7d103f-e23b-473d-a9e5-ad25b5a50c84)
![valid failed되었을때 예시](https://github.com/f-lab-clone/ticketing-backend/assets/33713012/436b4643-fdc9-4bf4-91ed-55eb09f92bff)

반환하는 예시 입니다.

2023-09-19 11:18 UTC, junha-ahn requested changes
추가 사항 
- 404 Page Not Found
- 500 Error (서비스 전체 단위의 에러 핸들링)

또 그와 관련된 테스트도 있었으면 좋겠습니다

2023-09-19 11:18 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/service/ReservationService.kt
> +        val event = eventRepository.findByIdWithPesimisticLock(eventId) ?: throw CustomException(ErrorCodes.EVENT_NOT_FOUND)
개인적으로 아래와 같은 방향이 더 좋을 것 같습니다. 
- `CustomException`에 `ErrorCodes`를 반복해서 주입하는 형태보다, 각각의 독립적인 CustomError 객체를 정의

```kotlin
throw CustomException(ErrorCodes.EVENT_NOT_FOUND)

# 제가 생각하기에 더 명시적이고 좋은 방법
throw EventNotFoundException()
```

2023-09-19 11:18 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/utils/exception/ErrorCodes.kt
> +    RESERVATION_NOT_FOUND(HttpStatus.NOT_FOUND, "예약 정보를 찾을 수 없습니다"),
`EntityNotFound` 는 하나의 에러코드만 있어도 좋을 것 같네요. 

생각을 해봤는데

시나리오1) 예약을 할려는데 Event가 존재하지 않는다
- 화면에서 "이벤트가 존재하지 않습니다"라고 띄워야할 상황은 발생하지 않을 것 같습니다
- 이유: 에초에 일반적인 유저가(개발과정이 아닌 이상) 존재하지 않는 이벤트 ID를 통해 예약을 하는 상황이 극히 드물다.

시나리오2) Event 하나를 조회했는데  Event가 존재하지 않는다
- 이와 같은 경우엔 EntityNotFound로 에러 메세지 출력 컨트롤이 가능합니다.

위 이유로 나중에 필요에 의해 Entity Not Found를 세분화 해도 될 것 같습니다. 
- 물런 페이지 NotFound는 당연히 필요합니다.

2023-09-19 11:26 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/service/ReservationService.kt
> +        val event = eventRepository.findByIdWithPesimisticLock(eventId) ?: throw CustomException(ErrorCodes.EVENT_NOT_FOUND)
그리고 갑자기 든 의문인데

```kt
 fun createReservation(eventId: Int, userId: Int): Reservation 
```

이렇게 응답값을 정의했는데 Throw 하는건 해당하는바가 없는건가요?

2023-09-21 10:46 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/service/ReservationService.kt
> +        val event = eventRepository.findByIdWithPesimisticLock(eventId) ?: throw CustomException(ErrorCodes.EVENT_NOT_FOUND)
> 개인적으로 아래와 같은 방향이 더 좋을 것 같습니다.
> 
> * `CustomException`에 `ErrorCodes`를 반복해서 주입하는 형태보다, 각각의 독립적인 CustomError 객체를 정의
> 
> ```kotlin
> throw CustomException(ErrorCodes.EVENT_NOT_FOUND)
> 
> # 제가 생각하기에 더 명시적이고 좋은 방법
> throw EventNotFoundException()
> ```

상황에 맞는 Error클래스를 작성한다면 명시적일수 있으나,
그렇게 진행하면 각 Error마다 클래스파일을 만들어주어야 합니다.
그리고 GlobalExceptionHandler에 error 들 각각을 어떻게 핸들할껀지 한개씩 정의해줘야합니다.

찾아보니  상황에 맞는 Exception 클래스들을 만들었다가 이방법으로 리팩토링한분도 있네요 
[link](https://kdhyo98.tistory.com/93)

2023-09-21 10:47 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/service/ReservationService.kt
> +        val event = eventRepository.findByIdWithPesimisticLock(eventId) ?: throw CustomException(ErrorCodes.EVENT_NOT_FOUND)
> 그리고 갑자기 든 의문인데
> 
> ```kotlin
>  fun createReservation(eventId: Int, userId: Int): Reservation 
> ```
> 
> 이렇게 응답값을 정의했는데 Throw 하는건 해당하는바가 없는건가요?

질문을 이해 못했습니다

2023-09-21 12:07 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/service/ReservationService.kt
> +        val event = eventRepository.findByIdWithPesimisticLock(eventId) ?: throw CustomException(ErrorCodes.EVENT_NOT_FOUND)
>  handler를 개별로 만들 필요가 없어졌다

이 부분을 생각 못했네요. resolve하겠습니다!

2023-09-21 15:46 UTC, junha-ahn requested changes
500에러와 404에러에 대한 테스트코드 작성 부탁드립니다.

2023-09-21 15:46 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/dto/ResponseDTO.kt
`timestamp`와 `path`는 ErrorResponse일때만 반환할 필요는 없을 겁니다.

최대한 통일성을 유지해주세요.

2023-09-21 15:46 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/utils/exception/ErrorCodes.kt
> +    VALIDATION_FAILED(HttpStatus.BAD_REQUEST, "유효성 검증에 실패하였습니다.", -10001),
전부 음수보단 양수로 정의하는게 좋을것 같습니다!

2023-09-23 00:40 UTC, junha-ahn requested changes

2023-09-23 00:40 UTC, junha-ahn commented on src/integrationTest/kotlin/com/group4/ticketingservice/ResponseFormatTest.kt
> +        assertNotNull(errorResponse.message)
중복 라인

2023-09-23 00:40 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/config/SecurityConfig.kt
> +                it.requestMatchers("/reservations").authenticated()
예약 조회 수정 등 모두 권한이 필요하지 않나요?

2023-09-23 00:40 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/utils/exception/ErrorCodes.kt
> +    NOT_OWNER_OF_RESERVATION(HttpStatus.FORBIDDEN, "예약의 주인이 아닙니다.", 30000),
해당 오류도 `ENTITY_NOT_FOUND`와 같이 실제 유저는 발생하지 않을 오류입니다. 
특정 ENTITY마다 다른 에러코드를 만들어도 좋지만, 당장은 `FORBIDDEN`등의 에러 코드로 통일해도 좋을것 같습니다.

2023-09-23 00:43 UTC, junha-ahn requested changes

2023-09-23 00:43 UTC, junha-ahn commented on src/integrationTest/kotlin/com/group4/ticketingservice/ResponseFormatTest.kt
해당 테스트들 integrationTest가 아니라 UnitTest에서는 못하는건가요?

2023-09-23 02:07 UTC, minjun3021 commented on src/integrationTest/kotlin/com/group4/ticketingservice/ResponseFormatTest.kt
가능합니다 이동시키겠습니다

2023-09-23 03:17 UTC, junha-ahn approved these changes

2023-09-24 06:16 UTC, ParkJeongseop commented on src/integrationTest/kotlin/com/group4/ticketingservice/User/UserControllerTest.kt
> +    fun `GET_api_users_access_token_info should return HTTPStatus 403 Forbidden when header not exist`() {
토큰헤더가 없는경우는 401아닙니까?

2023-09-24 06:16 UTC, ParkJeongseop commented on src/main/kotlin/com/group4/ticketingservice/config/SecurityConfig.kt
> +    // private val allowedUrls = arrayOf("/", "/api-docs.yaml", "/health", "/users/signup", "/bookmarks/**", "/reservations/**", "/events/**", "/actuator/**")
주석 지워주세요

2023-09-27 13:56 UTC, ParkJeongseop approved these changes
LGTM

2023-09-27 14:15 UTC, ParkJeongseop reviewed
확인바랍니다.

2023-09-27 14:15 UTC, ParkJeongseop commented on src/integrationTest/kotlin/com/group4/ticketingservice/User/UserControllerTest.kt
> +    fun `GET_api_users_access_token_info should return HTTPStatus 401 Unauthorized when jwt is expired`() {
이부분은 403이 맞는거같습니다.
JWT토큰이 헤더에없으면 401 Unauthorized, JWT토큰이 만료되면 403 Forbidden인거같습니다.
[[HTTP] HTTP 상태 401(Unauthorized) vs 403(Forbidden) 차이](https://mangkyu.tistory.com/146)

2023-09-30 06:22 UTC, merged