Feat/40 validation
f-lab-clone/ticketing-backend pull request #93
Opened 2023-09-27 07:23 UTC by ParkJeongseop

#  What is this PR?
- Github Issue: #40 

# Key Changes

# Test Checklist

2023-09-27 07:32 UTC, minjun3021 reviewed
수정 필요

2023-09-27 07:32 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/dto/EventDto.kt
> +    val maxAttendees: Int?
음수를 체크하는 어노테이션을 추가해주세요 
[annotation list](https://dev-coco.tistory.com/123)

2023-09-27 07:32 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/dto/EventDto.kt
> +    val reservationEndTime: OffsetDateTime?,
시간 관련 어노테이션 추가해주세요 
[annotation list](https://dev-coco.tistory.com/123)

2023-09-27 07:32 UTC, minjun3021 commented on src/main/kotlin/com/group4/ticketingservice/dto/ReservationDto.kt
>  )
음수를 체크하는 어노테이션을 추가해주세요
[annotation list](https://dev-coco.tistory.com/123)

2023-09-27 09:32 UTC, junha-ahn requested changes

2023-09-27 09:32 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/dto/EventDto.kt
> +    @field:Size(min = 2, max = 255)
event 한글자도 괜찮을거같네요.

2023-09-27 15:05 UTC, junha-ahn commented on src/integrationTest/kotlin/com/group4/ticketingservice/TimeE2ETest.kt
> +            "\"reservationEndTime\":\"2044-01-01T23:00:00.001+09:00\"," +
수정 목적이 있을까요?

2023-09-27 15:05 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/dto/EventDto.kt
> +    val title: String?,
이런 항목들 OpenDocs 만들때 포함됩니까?

2023-09-28 04:16 UTC, ParkJeongseop commented on src/integrationTest/kotlin/com/group4/ticketingservice/TimeE2ETest.kt
> +            "\"reservationEndTime\":\"2044-01-01T23:00:00.001+09:00\"," +
이벤트 추가시 미래 날짜로만 설정할 수 있도로 Validation 등록하여서 테스트시에도 현재날짜로 부터 미래로만 등록 테스트 할수 있어서 테스트 데이터를 수정하였습니다.

2023-09-28 04:22 UTC, ParkJeongseop commented on src/main/kotlin/com/group4/ticketingservice/dto/EventDto.kt
> +    val title: String?,
Length만 포함되고 이외의 Validation은 규격외 내용이라 반영되지않습니다.

2023-09-28 04:35 UTC, ParkJeongseop commented on src/main/kotlin/com/group4/ticketingservice/dto/EventDto.kt
> +    val title: String?,
OpenAPI 규격에 맞는경우에는 생성되고 지원하지않는 항목은 포함되지않습니다.
Length는 규격내 항목으로 포함되고, Future같이 날짜관련 항목은 포함되지않습니다.
[Swagger Data Types](https://swagger.io/docs/specification/data-models/data-types/)

2023-09-28 04:35 UTC, merged